<div class="container">
    <div class="condition">
    <div class="col-lg-12 col-md-12">
        <h1 class="content-title">Privacy Policy</h1>

<div class="text-block">
           
            <p>Last updated: August 19, 2020</p>
            <p>At Paulsons, we value the trust bestowed upon us by You. We want You to have the best possible & seamless shopping experience when You visit Our website and shop there. We value Your concerns about online privacy and security and We make every effort to ensure the same. We also believe in complete transparency. This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
            <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
       
            <h3>Interpretation and Definitions</h3>
            <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
  
            <h4>Definitions</h4>
                <p>For the purposes of this Privacy Policy:</p>
                <ul>
                <li>
                Account means a unique account created for You to access our Service or parts of our Service.
                </li>
                <li>
                Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to PAULSONS, E-8, Ground Floor, Lajpat Nagar - 2, New Delhi - 110024.
                </li>
<li>Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
<li>Country refers to: Delhi, India</li>
<li>Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
<li>Personal Data is any information that relates to an identified or identifiable individual.</li>
<li>Service refers to the Website.</li>
<li>Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate </li>
<li>the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used</li>
<li>Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
<li>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
<li>Website refers to paulsonsonline, accessible from www.paulsonsonline.com</li>

<li>You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>

                <h3>Types of Data Collected</h3>
                <h4>Personal Data</h4>
                <p>While using Our Service, You can browse Our Website without providing any personal information. At certain stages or nature of the activity, We may ask You to provide Us with certain personally 
                </p>

                <p>identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
   <p>Email address</br>
First name and last name</br>
Phone number</br>
Address, State, Province, ZIP/Postal code, City</br>
Usage Data</br>
</p>

<h4>Usage Data</h4>
<p>Usage Data is collected automatically when using the Service.</p>
<p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
   <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
   
   
   <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device</p>
   
   
   <h4>Information from Third-Party Social Media Services</h4>
   <p>The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:</p>
   
<ul>
<li>Google

</li>
<li>Facebook</li>
</ul>
<p>If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.</p>
  
  <p>You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.</p>
  
  <h3>Tracking Technologies and Cookies</h3>

  <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyse Our Service.</p>
  
  
  <p>You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</p>
  <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web browser. Learn more about cookies: All About Cookies.</p>
  
  <p>We use both session and persistent Cookies for the purposes set out below:</p>

  <p>Necessary / Essential Cookies</p>
  <p>Type: Session Cookies</p>
  <p>Administered by: Us
</p>

<p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent </p>
  <p>fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
  
  <h4>Cookies Policy / Notice Acceptance Cookies</h4>
  
  <p>Type: Persistent Cookies</p>
  <p>Administered by: Us</p>
  <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
  <h34>Functionality Cookies</h4>
  <p>Type: Persistent Cookies</p>
  <p>Administered by: Us</p>

  <p>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
  
  <h4>Tracking and Performance Cookies</h4>
  <p>Type: Persistent Cookies</p>
  <p>Administered by: Third-Parties</p>
  <p>Purpose: These Cookies are used to track information about traffic to the Website and how users use the Website. The information gathered via these Cookies may directly or indirectly identify you as an individual visitor. This is because the information collected is typically linked to a pseudonymous identifier associated with the device you use to access the Website. We may also use these Cookies to test new pages, features or new functionality of the Website to see how our users react to them.</p>
  <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
  
  <h3>Use of Your Personal Data</h3>
  <p>The Company may use Personal Data for the following purposes:</p>

  <ul>
  
  <li>•	To provide and maintain our Service, including to monitor the usage of our Service.</li>
<li>•	To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
<li>•	For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
<li>•	To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
<li>•	To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
<li>•	To manage Your requests: To attend and manage Your requests to Us.</li>
<li>We may share your personal information in the following situations:</li>
<li>•	With Service Providers: We may share Your personal information with Service Providers to monitor and analyse the use of our Service, to advertise on third party websites to You after You visited our Service, for payment processing, to contact You.</li>

<li>•	With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honour this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
<li>•	With Business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
  </ul>

<h3>Retention of Your Personal Data</h3>
<p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
<p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
 
 <h3>Transfer of Your Personal Data</h3>

 <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
 <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
 
 <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
 
 <h3>Disclosure of Your Personal Data</h3>
 <h4>Law enforcement</h4>
 <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
 <h4>Other legal requirements</h4>

<p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
<ul>

<li>•	Comply with a legal obligation
</li>
<li>•	Protect and defend the rights or property of the Company
</li>
<li>•	Protect the personal safety of Users of the Service or the public
</li>
<li>•	Protect against legal liability</li>
</ul>
<h3>Security of Your Personal Data</h3>
<p>The security of Your Personal Data is important to Us, and Your information is protected in many ways. It resides on secure servers that only selected Paulsons personnel have access via password. Your personal information is stored in an encrypted manner. We take all possible measures to maintain the security of Your personal information but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

<h3>Detailed Information on the Processing of Your Personal Data</h3>
<p>Service Providers have access to Your Personal Data only to perform their tasks on Our behalf and are obligated not to disclose or use it for any other purpose.</p>

<h4>Analytics</h4>
<p>We may use third-party Service providers to monitor and analyse the use of our Service.</p>
<p>Google Analytics</p>
<p>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network.</p>
<p>You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics </p>
<p>JavaScript (ga.js, analytics.js and dc.js) from sharing information with Google Analytics about visits activity.</p>

<p>For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: https://policies.google.com/privacy</p>

<h3>Email Marketing</h3>

<p>We may use Your Personal Data to contact You with newsletters, marketing or promotional materials and other information that may be of interest to You. You may opt-out of receiving any, or all, of these communications from Us by following the unsubscribe link or instructions provided in any email We send or by contacting Us.</p>
<p>We may use Email Marketing Service Providers to manage and send emails to You.</p>
<h4>Mailchimp</h4>

<p>Mailchimp is an email marketing sending service provided by The Rocket Science Group LLC.</p>

<p>For more information on the privacy practices of Mailchimp, please visit their Privacy policy: https://mailchimp.com/legal/privacy/</p>

<h3>Payments</h3>
<p>We may provide paid products and/or services within the Service. In that case, we may use third-party services for payment processing (e.g. payment processors).</p>
<p>We will not store or collect Your payment card details. That information is provided directly to Our third-party payment processors whose use of Your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>
  
  <h4>Cashfree</h4>
  <p>Their Privacy Policy can be viewed at https://www.cashfree.com/privacypolicy.html</p>
  <h3>Behavioral Remarketing</h3>
  <p>The Company uses remarketing services to advertise on third party websites to You after You visited our Service. We and Our third-party vendors use cookies to inform, optimize and serve ads based on Your past visits to our Service.</p>
   
   <h4>Google Ads (AdWords)</h4>
   <p>Google Ads (AdWords) remarketing service is provided by Google Inc.</p>

   <p>You can opt-out of Google Analytics for Display Advertising and customise the Google Display Network ads by visiting the Google Ads Settings page: http://www.google.com/settings/ads
Google also recommends installing the Google Analytics Opt-out Browser Add-on - https://tools.google.com/dlpage/gaoptout - for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics.
</p>
<p>For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: https://policies.google.com/privacy</p>
  
  <h4>Facebook</h4>
  <p>Facebook remarketing service is provided by Facebook Inc.</p>
  <p>You can learn more about interest-based advertising from Facebook by visiting this page: https://www.facebook.com/help/164968693837950</p>
  
  <p>To opt-out from Facebook's interest-based ads, follow these instructions from Facebook: https://www.facebook.com/help/568137493302217</p>
  <p>Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating </p>
  
  <p>companies through the Digital Advertising Alliance in the USA http://www.aboutads.info/choices/, the Digital Advertising Alliance of Canada in Canada http://youradchoices.ca/ or the European Interactive Digital Advertising Alliance in Europe http://www.youronlinechoices.eu/, or opt-out using your mobile device settings.</p>
 <p>For more information on the privacy practices of Facebook, please visit Facebook's Data Policy: https://www.facebook.com/privacy/explanation</p>
 
 <h3>Links to Other Websites</h3>
 <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
  <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
   <h3>Changes to this Privacy Policy</h3>
   <p>We may update our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
    
    <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
    <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
   
   <h3>Contact Us</h3>
   <p>If you have any questions about this Privacy Policy, You can contact us:</p>
   <p>By email: support@paulsonsonline.com</p>
   <p>By visiting this page on our website: www.paulsonsonline.com/contact</p>
    </div>
    </div>
</div>
</div>
