<div class="container">
    <div class="condition">
    <div class="col-lg-12 col-md-12">
        <h1 class="content-title">TERMS OF USE
karzanddolls</h1>
        <div class="text-block">
           
         
            <h3>1. GENERAL</h3>
            
            <p>
                 a) This document is an electronic record in terms of Information Technology Act,
2000 and rules there under as applicable and the amended provisions
pertaining to electronic records in various statutes as amended by the
Information Technology Act, 2000. This electronic record is generated by a
computer system and does not require any physical or digital signatures.
            </p>
          
            <p>
               b) This document is published in accordance with the provisions of Rule 3 (1) of
the Information Technology (Intermediaries guidelines) Rules, 2011 that
require publishing the rules and regulations, privacy policy and Terms of Use
for access or usage of www.karzanddolls.com 
            </p>

            <p>
                c) The domain name www.karzanddolls.com (&quot;Website&quot;), including its online
services, such as use of software on Website and information, articles , news,
blogs and text, graphics, images and information obtained from service
providers and any other material contained on the Website (&quot;Materials&quot;) is
owned and operated by PAMASHA INTERNET PRIVATE
LIMITED(“Company”) a Private Limited Company, incorporated under the
provisions of the Companies Act, 2013, and having its registered office at:
602,A-Block, Naurang House,21, K G Marg, New Delhi 11001, where
such expression shall, unless repugnant to the context thereof, be deemed to
include its respective representatives, administrators, employees, directors,
officers, agents and their successors and assigns.
            </p>
            <p>
                d) For the purpose of these Sellers Terms of Use (“Terms”), wherever the context
so requires,</br>

i) The term ‘You’ &amp; ‘Seller’ shall mean any legal person or entity accessing
using this Website to services provided or registered on this Website, who
is competent to enter into binding contracts, as per the provisions of the
Indian Contract Act, 1872;</br>
ii) The terms ‘We’, ‘Us’ &amp;‘Our’ shall mean the Website and/or the Company,
as the context so requires.</br>


iii) The terms ‘Party’&amp; ‘Parties’ shall respectively be used to refer to the
Seller and the Company individually and collectively, as the context so
requires.
            </p>

            <p>
                e) The headings of each section in these Terms are only for the purpose of
organizing the various provisions under these Terms in an orderly manner,
and shall not be used by either Party to interpret the provisions contained
herein in any manner. Further, it is specifically agreed to by the Parties that
the headings shall have no legal or contractual value.
            </p>

            <p>
              f) The use of the Website by the Seller is solely governed by these Terms as well
as the Privacy Policy (“Policy”), available on Website and any modifications or
amendments made thereto by the Company from time to time, at its sole
discretion. Visiting the home page of the Website and/or using any of the
services provided on the Website shall be deemed to signify the Seller’s
unequivocal acceptance of these Terms and the aforementioned Policy, and the
Seller expressly agrees to be bound by the same. The Seller expressly agrees
and acknowledges that the Terms and Policy are co-terminus, and that expiry /
termination of either one will lead to the termination of the other, save as
provided in Clause 4 hereunder.  
            </p>

            <p>
                g) The Seller unequivocally agrees that these Terms and the aforementioned
Policy constitute a legally binding agreement between the Seller and the
Company, and that the Seller shall be subject to the rules, guidelines, policies,
terms, and conditions applicable to any service that is provided by the Website,
and that the same shall be deemed to be incorporated into these Terms, and
shall be treated as part and parcel of the same. The Seller acknowledges and
agrees that no signature or express act is required to make these Terms and
the Policy binding on the Seller, and that the Seller’s act of visiting the any part
of the Website constitutes the Seller’s full and final acceptance of these Terms
and the aforementioned Policy.
            </p>

            <p>
                h) The Company reserves the sole and exclusive right to amend or modify these
Terms without any prior permission or intimation to the Seller, and the Seller
expressly agrees that any such amendments or modifications shall come into
effect immediately. The Seller has a duty to periodically check the terms and
stay updated on its requirements. If the Seller continues to use the Website
following such a change, the Seller will be deemed to have consented to any
and all amendments / modifications made to the Terms. In so far as the Seller
complies with these Terms, he/she is granted a personal, non-exclusive, non-
transferable, revocable, limited privilege to enter and use the Website.
            </p>


  <h3>2. OUR SERVICES</h3>  
  <p>
      The karzanddolls is India’s vital innovative Online storewith large variety of Brands
and products and all national/International brands in the catalogue. It’s idea to
create the common platform for buyers and sellers to fulfil their day to day
requirement. Buyers have to place the orders by filling in the details; the products
will be delivered right at their doorsteps. Registered Sellers are solely responsible
for quality of goods they provide. The Company accepts no responsibility for any
legal or financial consequences or implications arising out of use of the Website,
including any Online Services, or Materials. The Company disclaims any
warranties express or implied connected with use of the Website including its
quality, availability or accuracy, which are provided on an &quot;AS IS&quot; basis.
      
  </p>

<h3>3. ELIGIBILITY</h3>

<p>
    The Seller represents and warrants that he/she is competent and eligible to enter
into legally binding agreements and that he/she has the requisite authority to bind
himself/herself to these Terms, as determined solely by the provisions of the
Indian Contract Act, 1872. The Seller may not use this Website if he/she is not
competent to contract under the Indian Contract Act, 1872, or is disqualified from
doing so by any other applicable law, rule or regulation currently in force.
</p>

<h3>
     4. TERM
</h3>
   
<p>
    These Terms shall continue to form a valid and binding contract between the
Parties, and shall continue to be in full force and effect until:
</p>



<p>
    a) The Seller continues to access and use the Website; or</br>
b) The Transaction between the Parties, if any, concludes to the satisfaction of
both Parties;
    
</p>

<p>
    Whichever is longer? The Parties agree that certain portions of these Terms
(“Sections”), such as Sections 13, 14, 16&amp;18 shall continue to remain in full
force and effect indefinitely, even after the expiry or termination of these Terms as
contemplated herein.   
            
</p>
<h3>5. COVENANTS OF SELLER</h3>
<p>
    The Seller hereby covenants with the Company as under:
</p>

<p>
    a) The Seller shall not approach and/or offer discounts to customers received through
the karzanddolls, In case found doing such activities the Company has the right to
break this agreement with immediate effect and Seller has no right to claim for any
pending dues.
</p>
<p>
    b) Not to send any kind of promotion material or any such material, which is,
derogatory to and/or adverse to the interests financial or otherwise of the Company,
to the customer either along with the services provided or in any manner
whatsoever.
</p>


<p>
    c) Not to do any act/deal in a thing / products/goods/services which are either
banned/prohibited by law or violates any of the intellectual property right of any
party in respect of such good/services/product/thing.
</p>

<p>
 d) The Seller declares that it has all rights and authorizations in respect of intellectual
property rights and is authorized to sale/provide/license such services to the
customer. The “Seller” shall provide a copy of its authorization documents,
identification proofs and licenses (all or whichever applicable) to the Company at
the time of entering into the said agreement.   
</p>
<h3>
    6. TERMINATION
</h3>

<p>
  The Company reserves the right, in its sole discretion, to unilaterally terminate the
Seller’s access to the products and services offered on the Website, or any portion
thereof, at any time, without notice or cause. The Seller shall continue to be bound
by these Terms, and it is expressly agreed to by the Parties that the Seller shall not
have the right to terminate these Terms till the expiry of the same, as described in
Section 3 hereinabove.  
</p>
<h3>+
7. FACILITIES TO BE RENDERED BY THE WEBSITE
</h3>

<p>
    i. To provide a log in id and password to enable registered Seller to create,
update, and make any changes in its Profile Page as required.
    
</p>

<p>
    ii. To facilitate e-mail communication between Website&#39;s registered Sellers
and the registered customer to enable Sellers to make and receive queries.
</p>

<p>
    iii. karzanddolls does not make any representations or warranties regarding
specifics (such as quality, value, and salability) of the items or services
proposed to be sold, offered to be sold or purchased on the Website.
</p>

<p>
    iv. The karzanddolls is only a platform that can be utilized by you to reach a
larger customer base to sell items or services. karzanddolls only provides a
platform for communication and it is agreed that the contract for sale of any
products or services shall be a strictly bipartite contract between seller and
the buyer.
</p>

<p>
   v. The karzanddolls does not at any point of time during a transaction between
Seller and a buyer on the Website come into or takes possession of any of the
products or services offered by Seller, gain title to or have any rights or
claims over the products or services offered by you to the buyer. 
</p>

<p>
   vi. By using this Website, and providing his/her contact information to the
Company through the Website, the Seller hereby agrees and consents to




receiving calls, auto dialled and/or pre-recorded message calls, e-mails and
SMSs from the Company and/or any of its affiliates or partners at any time,
subject to the Policy. In the event that the Seller wishes to stop receiving any
such marketing or promotional calls / email messages / text messages, the
Seller may send an e-mail to the effect to hello@paulsonsonline.com with the
subject Stop sending promotional emails]. The Seller agrees and
acknowledges that it may take up to seven (7) business days for the
Company to give effect to such a request by the Seller. 
</p>

<p>
   The Seller expressly agrees that notwithstanding anything contained hereinabove,
he/she may be contacted by the Company or any of its affiliates / partners relating
to any service availed of by the Seller on the Website or anything pursuant
thereto. 
</p>

<p>
  It is expressly agreed to by the Parties that any information shared by the Seller
with the Company shall be governed by the Policy.  
</p>

<h3>8. KYC FULFILMENT</h3>

<p>
    i. “KYC” stands for Know Your Customer and refers to the various norms, rules,
laws and statutes issued by Reserve Bank of India from time to time.
</p>

<p>
   ii. In order to use the platform to sell products, Sellers need to have the following:-
<p style="margin-left: 10px">
    i. GSTIN Number (GSTIN/TIN number not mandatory for few categories).</br>
ii. PAN Card of Proprietor as well as of the Business of the Seller.</br>
iii. Aadhar Card of the Proprietor. </br>
iv. Brand authorization letter/Trademark Registration Certificate or
Acknowledgement.</br>
v. Bank Account with KYC Documents (Address Proof and Cancelled
Cheque). 
</p>

</p>

<p>
    iii. Website is required to procure personal identification details from the Seller
before any Services/Goods can be delivered and at the time of Registration and/
or on a later date, for availing and / or continuation of Website.
</p>

<p>
   iv. We reserve the right to discontinue Services/ reject applications for registration
at anytime if there are discrepancies in information and/or documentation
provided by you. 
</p>

<p>
    v. If the particulars provided by you in the KYC documents do not match with the
details mentioned in the KYC enrolment form, then Website has the right to
forfeit the balance amount in your wallet.
</p>

<p>
   vi. Subject to guidelines/notifications issued by RBI from time to time these
limitations may be reviewed and modified at the discretion Website without
prior intimation you. 
</p>
<h3>
    9. CHARGES&amp; PAYMENT
</h3>
<p>
 The Company shall not charge any fee for listing products/items for sale on the
website of the Company. It shall be free of cost. Although, as a consideration for
providing platform for revenue to the Seller, the Company shall charge from the
Seller as follows:   

<p style="margin-left: 10px">
    a) <strong>Commission Fee –</strong>  The Company will charge certain % percentage of
commission on the products sold by the Seller through this online website
depending upon the categories and sub-categories.</br>

b) <strong>Collection Fee –</strong> The Company will charge % Collection Fee for the CASH
ON DELIVERY orders made to the customers/user on behalf of the Seller
or Payment Gateway Charges, if payment made through online payment
gateway by the customers / users.</br>
c) <strong>Courier Charges-</strong>  Company will charge certain amount of courier
charges from the Vendors. Please refer courier charges and policy on
shipment section.</br>
d) <strong>Fixed fees-</strong>  Certain amount on every transaction</br>

e)  GST on all the above components shall be charge separately.</br>


f) Other applicable govt taxes as per e-commerce policy.</br>

g) The Company shall process the payment to the Seller account within 7-10
days after the date of delivery of the product after deducting above
mentioned charges through NEFT or Paytm, or RTGS etc etc.

    
</p>
</p>

<p>
    
However, the Company reserves the right to amend this fee policy for any or all
goods offered or sold. In such an event, the Seller will be intimated of the same
when he/she attempts to access the Website, and the Seller shall have the option of
declining to avail of the services offered on the Website. Any such change, if made,
shall come into effect immediately upon such change being notified to the Seller,
unless specified otherwise.
</p>
<h3>
    10. TERMS, CONDITIONS AND DUTIES OF THE SELLER
</h3>

<p>
    a. It is the duty of Seller to provide true/accurate / complete information about
its shop/store, locality of shop, and all the details relating thereof.
</p>

<p>
    b. It is duty of Seller to ensure that he is an authorized Brand Seller of the
product.
</p>

<p>
   c. It is the duty of Seller not to force any customer for the purchase of product
in the greed of commission. 
</p>

<p>
d. The Seller is allowed to do advertisement of the company’s product at their
individual capacity.   
</p>
<p>
   e. It is the duty of the seller that all listed items must be kept in stock for
successful fulfillment of sales. 
</p>
<p>
    f. It is the duty of the seller not to mislead the description of the item and
describe the actual condition of the product.
</p>

<p>
  g. It is the duty of Seller to check the products on regular basis to avoid delay
for shipping, if he fails to do so than he will be held liable for all the
injuries/harm/loss suffered by the customer/members.  
</p>

<p>
    h. It is the duty of Seller to guide the customer according to its specification (if
any).
</p>
<p>
   i. It is the duty of the seller to dispatch goods within 48 hours after order
confirmation. 
</p>
<p>
   j. The seller will be completely responsible for their products and any kind of
loss, damage, harm to any person or property. 
</p>
<p>
  k. The seller is bound to accept any refund under the refund policy.  
</p>

<p>
   l. The Seller need to pack its product properly with thick Packaging material to
avoid damage. Seller has to order packaging material from marketplace as
per their product size and quantity requirements. The Seller shall ensure that
only packaging material with brand name shall be used for delivery of
Products. Under no circumstances shall the packaging material contain
name, trademarks, logos, images, symbol, text, graphics, photographs and/or
other material or information belonging to any third party including any
marketplace other than brand name. 
</p>
<p>
    m. After packing the item keep it ready for our authorized courier partner for
pickup the product.
</p>

<p>
    n. The Seller needs to take care that the consignment/parcel should not contain
any letter of communication cash, any of hazardous nature or such things
that will infringe the Indian Postal Act 1983 or expressly prohibited by the
railway/airport authority or any other transport agency, shall not be
accepted.
</p>

<p>
    o. Logistic Partner shall not be liable for any loss arising due to the causes
beyond its control such as floods, accidents, fire, theft, war etc.
</p>

<p>
   p. Seller shall indemnify and hold the Company, harmless for any loss or
damage arising out of seller’s or Shipper’s failure to comply with any applicable laws or regulations and for breach of the following warranties and
representations.
</p>

<p>
    q. Seller has to provide at least 2 copies of invoice/declaration to facilitate
delivery.
</p>

<p>
   r. The Seller shall be solely responsible for the appropriate quality/ standard/
value of the goods provided by him, as agreed by the parties to the Contract.
If any commission/ omission on the part of Seller which resulted into
destruction or decrease/ diminishes the quality/standard/ value of the
services/goods provided by Seller, shall be under legal obligation to
compensate the Company for such goods. 
</p>

<p>
   s. The Seller owed duty or takes sole responsibility toward third party for any
dilemma which is occurred due act/ omission/ fault/ mistake on the part of
Seller during the selling the goods as agreed by the parties to the contract.
And also, Seller shall indemnify Company from fault. 
</p>

<p>
  t. The Seller shall not try to directly approach the Customers of the Company.
If any act/ omission on the part of Seller which is contrary to agreed terms
and condition, the Company is authorize to terminate the agreement and
Seller is under legal obligation to pay compensation to the firm due to
act/omission on the part of Seller.  
</p>

<p>
  u. The Seller shall provide same goods to the Company as agreed by the parties
or describe by the Seller at the time of the contract. If any
changes/modification occurs, the Company is not under legal obligation to
accept such services/products or Company may terminate the contract with
the Seller.  
</p>

<p>
    v. The Seller shall at all times during the pendency of this agreement endeavor
to protect and promote the interest of the Company and ensure that there
will be no damage to third party (client/customer) due to act/ omission on
the part of the Seller.
</p>

<p>
   w. Seller is bound not to cut, copy, distribute, modify, recreate, reverse
engineer, distribute, disseminate, post, publish or create derivative works
from, transfer, or sell any information or software obtained from the
Website. Any such use / limited use of the Website will only be allowed with
the prior express written permission of the Company. For the removal of
doubt, it is clarified that unlimited or wholesale reproduction, copying of the
content for commercial or non-commercial purposes and unwarranted
modification of data and information contained on the Website is expressly
prohibited. 
</p>

<p>
    x. Further undertakes not to:

<p style="margin-left: 22px;     line-height: 28px;">
    i. Abuse, harass, threaten, defame, disillusion, erode, abrogate,
demean or otherwise violate the legal rights of any other person or
entity; </br>

ii. Engage in any activity that interferes with or disrupts access to the
Website or the goods provided therein (or the servers and
networks which are connected to the Website);</br>

iii. Impersonate any person or entity, or falsely state or otherwise
misrepresent his/her affiliation with a person or entity;</br>

iv. Publish, post, disseminate, any information which is grossly
harmful, harassing, blasphemous, defamatory,
obscene, pornographic, paedophilic, libellous, invasive of
another&#39;s privacy, hateful, or racially, ethnically objectionable,
disparaging, relating or encouraging money laundering or
gambling, or otherwise unlawful in any manner whatever under
any law, rule or regulation currently in force; or unlawfully
threatening or unlawfully harassing including but not limited to
&quot;indecent representation of women&quot; within the meaning of the
Indecent Representation of Women (Prohibition) Act, 1986;</br>

v. Post any image/file/data that infringes the copyright, patent or
trademark of another person or legal entity;</br>


vi. Upload or distribute files that contain viruses, corrupted files, or
any other similar software or programs that may damage the
operation of the Website;</br>

vii. Download any file posted/uploaded by another Seller of the
Website that the Seller is aware, or should reasonably be aware,
cannot be legally distributed in such a manner;</br>

viii. Probe, scan or test the vulnerability of the Website or any
network connected to the Website, nor breach the security or
authentication measures on the Website or any network connected
to the Website. The Seller may not reverse look-up, trace or seek to
trace any information relating to any other Seller of, or visitor to,
the Website, or any other customer of the Website, including any
Seller account maintained on the Website not operated/managed
by the Seller, or exploit the Website or information made available
or offered by or through the Website, in any manner;</br>

ix. Disrupt or interfere with the security of, or otherwise cause harm
to, the Website, systems resources, accounts, passwords, servers
or networks connected to or accessible through the Websites or
any affiliated or linked websites;</br>

x. Collect or store data about other Sellers of the Website.</br>

xi. Use the Website or any material or content therein for any
purpose that is unlawful or prohibited by these Terms, or to solicit
the performance of any illegal activity or other activity which
infringes the rights of this Website or any other third party(ies);</br>

xii. Violate any code of conduct or guideline which may be applicable
for or to any particular product or service offered on the Website;
</br>
xiii. Violate any applicable laws, rules or regulations currently in

force within or outside India;</br>

xiv. Violate any portion of these Terms or the Policy, including but
not limited to any applicable additional terms of the Website
contained herein or elsewhere, whether made by amendment,
modification, or otherwise;</br>

xv. Threaten the unity, integrity, defence, security or sovereignty of
India, friendly relations with foreign states, or public order, or
cause incitement to the commission of any cognizable offence, or
prevent the investigation of any offence, or insult any other nation.</br>

xvi. Publish, post, or disseminate information that is false, inaccurate
or misleading;</br>

xvii. Directly or indirectly offer, attempt to offer, trade, or
attempt to trade, any item the dealing of which is prohibited or
restricted in any manner under the provisions of any applicable
law, rule, regulation or guideline for the time being in force.</br>

xviii. Commit any act that causes the Company to lose (in whole
or in part) the services of its internet service provider (&quot;ISP&quot;) or in
any manner disrupts the services of any other supplier/service
provider of the Company/Website;</br>

xix. Engage in advertising to, or solicitation of, other Sellers of the
Website to buy or sell any products or services not currently
displayed on the Website. The Seller may not transmit any chain
letters or unsolicited commercial or junk email/messages to other
Sellers via the Website. It shall be a violation of these Terms to use
any information obtained from the Website in order to harass,
abuse, or harm another person, or in order to contact, advertise to,
solicit, or sell to another Seller of the Website without the express
prior written consent of the Company.</br>
</p>
    
    
</p>
<p>
    The Seller hereby expressly authorises the Company/Website to disclose any and
all information relating to the Seller in the possession of the Company/Website to
law enforcement or other government officials, as the Company may in its sole
discretion, believe necessary or appropriate in connection with the investigation
and/or resolution of possible crimes, especially those involve personal injury and
theft / infringement of intellectual property. The Seller further understands that
the Company/Website might be directed to disclose any information (including the
identity of persons providing information or materials on the Website) as
necessary to satisfy any judicial order, law, regulation or valid governmental
request.
</p>
<p>
The Seller expressly agrees and acknowledges that the Company/Website has no
obligation to monitor the materials posted on the Website, but that it has the right
to remove or edit any content that in its sole discretion violates, or is alleged to
violate, any applicable law or either the spirit or letter of these Terms.
Notwithstanding this right, the Seller remains solely responsible for the content of
the materials posted on the Website by him/her. In no event shall the
Company/Website assume or be deemed to have any responsibility or liability for
any content posted, or for any claims, damages or losses resulting from use of any
such content and/or the appearance of any content on the Website. The Seller
hereby represents and warrants that he/she has all necessary rights in and to all
content provided as well as all information contained therein, and that such
content does not infringe any proprietary or other rights of any third party (ies),
nor does it contain any libellous, tortuous, or otherwise unlawful or offensive
material, and the Seller hereby accepts full responsibility for any consequences
that may arise due to the publishing of any such material on the Website.
</p>
<h3>
   11. TERMS, CONDITIONS AND DUTIES OF COMPANY 
</h3>

<p>
    i. The Company shall list item(s), products or goods for sale on the Website in
accordance with the policies.
</p>
<p>
  ii. The Company shall be legally authorized to sell the item(s) listed for sale on
Website and have all the necessary licenses and permits required for such sale.  
</p>

<h3>
 12. SUSPENSION OF SELLER ACCESS AND ACTIVITY   
</h3>

<p>
   Notwithstanding other legal remedies that may be available to it, the Company
may in its sole discretion limit the Seller’s access and/ or activity by immediately
removing the Seller’s access credentials either temporarily or indefinitely, or
suspend / terminate the Seller’s membership, and/or refuse to provide Seller with
access to the Website, without being required to provide the Seller with notice or
cause: 
</p>
<p>
    a) If the Seller is in breach any of these Terms or the Policy;
</p>
<p>
    b) If the Seller has provided wrong, inaccurate, incomplete or incorrect
information;
</p>
<p>
   c) If the Seller’s actions may cause any harm, damage or loss to the other Sellers
or to the Website/Company, at the sole discretion of the Company. 
</p>
<p>
   d) If Seller’ action copying or duplicating in any manner any of content or other
information available from the Website. 
</p>

<h3>
 13. INDEMNITY AND LIMITATIONS   
</h3>

<p>
    The Seller hereby expressly agrees to defend, indemnify and hold harmless the
Website and the Company, its directors, affiliate Sellers, employees, officers,
agents and their successors and assigns and against any and all claims, liabilities,
damages, losses, costs and expenses, including attorney&#39;s fees, caused by or arising
out of claims based upon the Seller&#39;s actions or inactions, including but not limited
to any warranties, representations or undertakings, or in relation to the non-
fulfilment of any of the Seller’s obligations under this Agreement, or arising out of
the Seller&#39;s infringement of any applicable laws, rules and regulations, including
but not limited to infringement of intellectual property rights, payment of
statutory dues and taxes, claims of libel, defamation, violation of rights of privacy
or publicity, loss of service by other subscribers, or the infringement of any other
rights of a third party.
</p>

<p>
    In no event shall the Company/Website be liable to compensate the Seller or any
third party for any special, incidental, indirect, consequential or punitive damages
whatsoever, including those resulting from loss of use, data or profits, whether or


not foreseeable, and whether or not the Company/Website had been advised of the
possibility of such damages, or based on any theory of liability, including breach of
contract or warranty, negligence or other tortuous action, or any other claim
arising out of or in connection with the Seller’s use of or access to the Website
and/or the products, services or materials contained therein.
</p>

<p>
 The limitations and exclusions in this section apply to the maximum extent
permitted by applicable law, and the Parties expressly agree that in the event of
any statute, rule, regulation or amendment coming into force that would result in
the Company/Website incurring any form of liability whatsoever, these Terms and
the Policy will stand terminated one (1) day before the coming into effect of such
statute, rule, regulation or amendment. It is further agreed to by the Parties that
the contents of this Section shall survive even after the termination or expiry of the
Terms and/or Policy.   
</p>

<h3>
    14. INTELLECTUAL PROPERTY RIGHTS
</h3>

<p>
    Unless expressly agreed to in writing, nothing contained herein shall give the Seller
a right to use any of the Website’s trade names, trademarks, service marks, logos,
domain names, information, questions, answers, solutions, reports, images, and
other distinctive brand features, save according to the provisions of these Terms.
All logos, trademarks, brand names, service marks, domain names, including
material, designs, and graphics created by and developed by the Website and other
distinctive brand features of the Website are the property of the Company.
Furthermore, with respect to the Website created by the Company, the Company
shall be the exclusive owner of all the designs, graphics and the like, related to the
Website.
</p>

<p>
    The Seller may not use any of the intellectual property displayed on the Website in
any manner that is likely to cause confusion among existing or prospective Sellers
of the Website, or that in any manner disparages or discredits the
Company/Website, to be determined in the sole discretion of the Company.
</p>

<p>
   The Seller is aware that the products displayed on the Website are the artistic
creations of their respective owners, and that all intellectual property, including


but not limited to copyrights, relating to said products resides with the said
owners, and that at no point does any such intellectual property stand transferred
from the aforementioned creators to the Website/Company, or to the Seller. The
Seller is aware that the Company merely provides a platform through which the
aforementioned products are listed for sale to the Sellers of the Website, and the
neither the Company nor the Website owns any of the intellectual property relating
to the products displayed on the Website. 
</p>

<p>
    The Seller is further aware that any reproduction or infringement of the
intellectual property of the aforementioned owners by the Seller will result in legal
action being initiated against the Seller by the respective owners of the intellectual
property so reproduced / infringed upon. It is agreed to by the Parties that the
contents of this Section shall survive even after the termination or expiry of the
Terms and/or Policy.
</p>

<h3>
    15. Audits
</h3>

<p>
    karzanddolls shall have the right to inspect and audit seller’s records and premises /
place of business through itself or through karzanddolls approved third party testing
agencies. Cost of such audit shall solely be borne by karzanddolls unless audit reflects
discrepancy in seller accounts / non-compliance with karzanddolls’sseller policies, in
which case cost of audit shall be borne by the seller.
</p>
<h3>
    16. DISLAIMER OF WARRANTIES AND LIABILITIES
</h3>

<p>
    a) Except as otherwise expressly stated on the Website, all products/services
offered on the Website are offered on an &quot;as is&quot; basis without any warranty
whatsoever, either express or implied.
</p>

<p>
    b) The Company/Website makes no representations, express or implied,
including without limitation implied warranties of merchantability and fitness
of a product for a particular purpose.
</p>
 
<p>
  c) The Website and the Company accepts no liability for any errors or omissions,

whether on behalf of itself or third parties, or for any damage caused to the
Customer, resulting from the use or misuse of any product purchased by the
Seller from the Website.  
</p>

<p>
  d) The Company/Website does not guarantee that the functions and services
contained in the Website will be uninterrupted or error-free, or that the
Website or its server will be free of viruses or other harmful components, and
the Seller hereby expressly accepts any and all associated risks involved with
the Seller’s use of the Website.  
</p>

<p>
   e) It is further agreed to by the Parties that the contents of this Section shall
survive even after the termination or expiry of the Terms and/or Policy. 
</p>

<h3>
    17. Compliance with Laws:
</h3>

<p>
   a) Seller shall comply with all the applicable laws (including without limitation Foreign
Exchange Management Act, 1999 and the rules made and notifications issued there
under and the Exchange Control Manual as may be issued by Reserve Bank of India
from time to time, Customs Act, Information and Technology Act, 2000 as amended
by the Information Technology (Amendment ) Act 2008, Prevention of Money
Laundering Act, 2002 and the rules made there under, GST Acts and rules made
there under, Foreign Contribution Regulation Act, 1976 and the rules made there
under, Income Tax Act, 1961 and the rules made there under, Legal Metrology Act,
2009 and the rules made thereunder, Export Import Policy of Government of India)
and obtain the necessary licences and permits applicable to them [including the
licences under the Foods Safety and Standards Act, 2006 for sale of products under
Food and Nutrition category] for using Payment Facility and Website. 
</p>

<p>
    b) All online bank transfers from valid bank accounts are processed using the gateway
provided by the respective issuing bank that supports payment facility to provide
these services to the Sellers. All such online bank transfers on payment facility are
also governed by the terms and conditions agreed to between a seller buyer and the
respective issuing bank.
</p>

<p>
    c)  In the event of sale of jewellery, seller shall ensure conducting of buyer KYC in
accordance with the prevention of anti-money laundering laws and other applicable
laws. karzanddollshereby disclaims any responsibility for conducting Buyer KYC.
</p>
<h3>
    18. SUBMISSIONS
</h3>

<p>
    Any comments, ideas, suggestions, initiation, or any other content contributed by
the Seller to the Company or this Website will be deemed to include a royalty-free,
perpetual, irrevocable, nonexclusive right and license for the Company to adopt,
publish, reproduce, disseminate, transmit, distribute, copy, use, create derivative
works, display worldwide, or act on such content, without additional approval or
consideration, in any media, or technology now known or later developed, for the
full term of any rights that may exist in such content, and the Seller hereby waives
any claim to the contrary. The Seller hereby represents and warrants that he/she
owns or otherwise controls all of the rights to the content contributed to the
Website, and that use of such content by the Company/Website does not infringe
upon or violate the rights of any third party. In the event of any action initiated
against the Company/Website by any such affected third party, the Seller hereby
expressly agrees to indemnify and hold harmless the Company/Website, for its use
of any such information provided to it by the Seller. The Company reserves its
right to defend itself in any such legal disputes that may arise, and recover the
costs incurred in such proceedings from the Seller.
</p>

<h3>
   19. Limited License 
</h3>

<p>
    The Company grants seller a limited, non-transferable, non-exclusive, non-sub
licensable, non-assignable and personal license to use &quot;Powered by karzanddolls&quot; name
and/or logo on seller’s invoice for transactions concluded on the Website. Further,
karzanddolls grants seller a limited, non-transferable, non-exclusive, non-sub-
licensable, non-assignable and personal license to use “karzanddolls” name and/or logo
on packing material used by seller for delivery of Products sold on the Website.
</p>

<h3>
    20. DISPUTE RESOLUTION AND JURISDICTION
</h3>
<p>
    It is expressly agreed to by the Parties hereto that the formation, interpretation
and performance of these Terms and any disputes/claim/refund/compensation
arising here from will be resolved through a two-step Alternate Dispute Resolution
(“ADR”) mechanism. It is further agreed to by the Parties that the contents of this
Section shall survive even after the termination or expiry of the Terms and/or
Policy.
</p>

<p>
    a) Mediation: In case of any dispute/claim/refund/compensation between the
parties, the Parties will attempt to resolve the same amicably amongst
themselves, to the mutual satisfaction of both Parties. In the event that the
Parties are unable to reach such an amicable solution within thirty (30) days of
one Party communicating the existence of a dispute to the other Party, the
dispute will be resolved by arbitration, as detailed herein below;
</p>

<p>
   b) Arbitration. In the event that the Parties are unable to amicably resolve a
dispute by mediation, said dispute will be referred to arbitration under
Arbitration and Conciliation Act, 1996 by a sole arbitrator to be appointed by
the Company, and the award passed by such sole arbitrator will be valid and
binding on both Parties. The Parties shall bear their own costs for the
proceedings, although the sole arbitrator may, in his/her sole discretion, direct
either Party to bear the entire cost of the proceedings. The seat of Arbitration
shall be in the state of Delhi, India. 
</p>

<p>
   The Parties expressly agree that the Terms, Policy and any other agreements
entered into between the Parties are governed by the laws, rules and regulations of
India, and that the Courts at Delhi shall have exclusive jurisdiction over any
disputes arising between the Parties. 
</p>

<h3>
  21. NOTICES  
</h3>
<p>
    Any or all kind of communication relating to any dispute or grievance experienced
by the Seller may be communicated to the Company by the Seller reducing the
same to writing, and sending the same to the registered office of the Company by
Registered Post Acknowledgement Due / Speed Post Acknowledgement Due
(RPAD / SPAD).
</p>



    </div>
        
      
        
        
        
        
        
        
        
        
        
        
                
    </div>
  
</div>
</div>
